package timmax.tilegame.basemodel.protocol;

public enum TypeOfTransportPackageOfClient {
    REQ_LOGIN/*,
    REQ_LOGOUT,
    REQ_GAME_TYPE_MAP,
    REQ_SELECT_GAME_TYPE,
    REQ_CREATE_GAME_SERIES,
    REQ_GAME_SERIES_MAP,
    REQ_SELECT_GAME_SERIES,
    REQ_GAME_MATCH_MAP,
    REQ_SELECT_GAME_MATCH,
    REQ_PLAYER_SIDE_MAP,
    REQ_SELECT_PLAYER_SIDE,
    REQ_DECLARE_READINESS,
    REQ_READINESS_MAP
*/
}